version: "3.8"

services:
  cassandra:
    image: library/cassandra:3.11
    volumes:
    - cassandra:/var/lib/cassandra
    healthcheck:
      test: cqlsh -e "show version"
  cortex:
    image: quay.io/cortexproject/cortex:v1.1.0
    ports:
    - 9009:9009
    volumes:
    - ./cortex-config.yaml:/etc/cortex-config.yaml:ro
    command: -config.file=/etc/cortex-config.yaml
    depends_on:
      - cassandra
  prometheus:
    image: prom/prometheus:v2.19.1
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana:7.0.3
    ports:
      - 3000:3000
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/main.yml:ro
      - grafana:/var/lib/grafana
    depends_on:
      - cortex

volumes:
  cassandra: {}
  grafana: {}

