global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: cortex
    static_configs:
      - targets: ["cortex:9009"]
remote_write:
  - url: http://cortex:9009/api/prom/push
